- project:
    name: sandbox
    github-org: trafodion

    jobs:
      - gate-noop
      - gate-{name}-check-for-binary
      - gate-{name}-puppet-lint
      - gate-{name}-puppet-syntax

- project:
    name: infra
    github-org: trafodion

    jobs:
      - gate-noop
      - gate-{name}-puppet-lint
      - gate-{name}-puppet-syntax
      - gate-{name}-check-for-binary

- project:
    name: core
    github-org: trafodion

    jobs:
      - traf-publish
      - core-regress-suites
      - gate-{name}-check-for-binary
      - phoenix_test
      - phoenix_quick

- project:
    name: manuals
    github-org: trafodion

    jobs:
      - gate-noop

- project:
    name: phoenix_test
    github-org: trafodion

    jobs:
      - gate-{name}-check-for-binary
      - phoenix_test-experimental
      - phoenix_test

- project:
    name: dcs
    github-org: trafodion

    jobs:
      - gate-{name}-check-for-binary
      - dcs-build
      - phoenix_test
      - phoenix_quick

- project:
    name: install
    github-org: trafodion

    jobs:
      - gate-{name}-check-for-binary
      - installer-build

- project:
    name: win-odbc64
    github-org: trafodion

    jobs:
      - gate-{name}-check-for-binary

