- project:
    name: sandbox
    github-org: trafodion

    jobs:
      - gate-{name}-check-for-binary
      - gate-{name}-puppet-lint
      - gate-{name}-puppet-syntax

- project:
    name: infra
    github-org: trafodion

    jobs:
      - gate-{name}-puppet-lint
      - gate-{name}-puppet-syntax
      - gate-{name}-check-for-binary

- project:
    name: core
    github-org: trafodion

    dist:
      - "cdh5.1"
      - "hdp2.1"
      - "cm5.1"

    jobs:
      - traf-publish
      - core-build-check-{dist}
      - core-regress-suites
      - gate-{name}-check-for-binary

- project:
    name: manuals
    github-org: trafodion

    jobs:
      - gate-noop

- project:
    name: phoenix_test
    github-org: trafodion

    dist:
      - "cdh5.1"
      - "hdp2.1"
      - "cm5.1"

    jobs:
      - gate-{name}-check-for-binary
      - phoenix-jobs

- project:
    name: dcs
    github-org: trafodion

    dist:
      - "cdh5.1"
      - "hdp2.1"
      - "cm5.1"

    jobs:
      - gate-{name}-check-for-binary
      - dcs-build
      - jdbc_test-{dist}
      - pyodbc_test-{dist}

- project:
    name: install
    github-org: trafodion

    jobs:
      - gate-{name}-check-for-binary
      - installer-build
      - installer-pub

- project:
    name: win-odbc64
    github-org: trafodion

    jobs:
      - gate-{name}-check-for-binary

